### PR TITLE
Update dip-201.md

### PR DESCRIPTION
**Pull request by dahliamalkhi**

### CODE REVIEW

**Review by zekun000 — APPROVED** [review]

**Review by aching — APPROVED** [review]

**Review by sasha8 — COMMENTED** [review]
The white paper is now online - we can add a link to it.

**Comment by aching** [comment]
@sasha8 can you submit a PR add the link - and perhaps remove the old paper?

**Comment by sasha8** [comment]
@aching Looks like I do not have write access to diem/dip.

(Here is the link: https://developers.diem.com/papers/diem-consensus-state-machine-replication-in-the-diem-blockchain/2021-08-17.pdf)

**Comment by zekun000** [comment]
I'll update the link

**Pull request merged**
