### PR TITLE
[Dip: 205] Add an initial draft DIP for State Sync v2.

### PR DESCRIPTION
**Pull request by JoshLind**
This PR is for an initial draft DIP of State Sync v2 (see issue: https://github.com/diem/dip/issues/204).

### CODE REVIEW

**Comment by JoshLind** [comment]
CC' @davidiw, @aching

Note: I can't add reviewers to this PR -- I guess this is intentional?

**Comment by davidiw** [comment]
I wonder these things too. I think there are limited permissions. I'll poke at it later.

**Comment by gregnazario** [comment]
@davidiw @aching Who's the DIP manager for this DIP?  And do we need this DIP?

**Comment by davidiw** [comment]
Informational DIPs are welcome. I do think we need a storage service DIP and if we aren't going to do storage service in the first pass, we should make a state sync v2 server DIP.

**Comment by davidiw** [comment]
I can take a look at this

**Pull request closed without merging**
